// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnnotationBox: typeof import('./src/components/pure/AnnotationBox/AnnotationBox.vue')['default']
    ApiError: typeof import('./src/components/base/ApiError/ApiError.vue')['default']
    ErrorMessage: typeof import('./src/components/pure/ErrorMessage/ErrorMessage.vue')['default']
    FormInput: typeof import('./src/components/base/FormInput/FormInput.vue')['default']
    GeneralButton: typeof import('./src/components/base/GeneralButton/GeneralButton.vue')['default']
    NamingFormular: typeof import('./src/components/feature/NamingFormular/NamingFormular.vue')['default']
    PasswordFormular: typeof import('./src/components/feature/PasswordFormular/PasswordFormular.vue')['default']
    ProfileAvatar: typeof import('./src/components/pure/ProfileAvatar/ProfileAvatar.vue')['default']
    ProfileBoxHeader: typeof import('./src/components/pure/ProfileBoxHeader/ProfileBoxHeader.vue')['default']
    ProfileConsent: typeof import('./src/components/feature/ProfileConsent/ProfileConsent.vue')['default']
    ProfileDetailBox: typeof import('./src/components/base/ProfileDetailBox/ProfileDetailBox.vue')['default']
    ProfileInfos: typeof import('./src/components/feature/ProfileInfos/ProfileInfos.vue')['default']
    ProfileNaming: typeof import('./src/components/feature/ProfileNaming/ProfileNaming.vue')['default']
    ProfilePassword: typeof import('./src/components/feature/ProfilePassword/ProfilePassword.vue')['default']
    ProfileRemove: typeof import('./src/components/feature/ProfileRemove/ProfileRemove.vue')['default']
    ProfileTimezone: typeof import('./src/components/feature/ProfileTimezone/ProfileTimezone.vue')['default']
    RemoveAccountFormular: typeof import('./src/components/feature/RemoveAccountFormular/RemoveAccountFormular.vue')['default']
    SimpleLabel: typeof import('./src/components/pure/SimpleLabel/SimpleLabel.vue')['default']
    'SimpleLabel.story': typeof import('./src/components/pure/SimpleLabel/SimpleLabel.story.vue')['default']
    StatusMessage: typeof import('./src/components/base/StatusMessage/StatusMessage.vue')['default']
    TabviewHeader: typeof import('./src/components/pure/TabviewHeader/TabviewHeader.vue')['default']
    Timezone: typeof import('./src/components/feature/Timezone/Timezone.vue')['default']
    'TSXUserProfile.ce': typeof import('./src/components/feature/TSXUserProfile/TSXUserProfile.ce.vue')['default']
    ViewLicense: typeof import('./src/components/feature/ViewLicense/ViewLicense.vue')['default']
    ViewProfile: typeof import('./src/components/feature/ViewProfile/ViewProfile.vue')['default']
  }
}
