// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnnotationBox: typeof import('./src/components/pure/AnnotationBox/AnnotationBox.vue')['default']
    ErrorMessage: typeof import('./src/components/pure/ErrorMessage/ErrorMessage.vue')['default']
    FormInput: typeof import('./src/components/base/FormInput/FormInput.vue')['default']
    GeneralButton: typeof import('./src/components/base/GeneralButton/GeneralButton.vue')['default']
    MessageBox: typeof import('./src/components/base/MessageBox/MessageBox.vue')['default']
    NamingFormular: typeof import('./src/components/feature/NamingFormular/NamingFormular.vue')['default']
    ProfileAvatar: typeof import('./src/components/pure/ProfileAvatar/ProfileAvatar.vue')['default']
    ProfileBoxHeader: typeof import('./src/components/pure/ProfileBoxHeader/ProfileBoxHeader.vue')['default']
    ProfileConsent: typeof import('./src/components/feature/ProfileConsent/ProfileConsent.vue')['default']
    ProfileDetailBox: typeof import('./src/components/base/ProfileDetailBox/ProfileDetailBox.vue')['default']
    ProfileInfos: typeof import('./src/components/feature/ProfileInfos/ProfileInfos.vue')['default']
    ProfileNaming: typeof import('./src/components/feature/ProfileNaming/ProfileNaming.vue')['default']
    ProfilePassword: typeof import('./src/components/feature/ProfilePassword/ProfilePassword.vue')['default']
    ProfileRemove: typeof import('./src/components/feature/ProfileRemove/ProfileRemove.vue')['default']
    ProfileTimezone: typeof import('./src/components/feature/ProfileTimezone/ProfileTimezone.vue')['default']
    RemoveAccount: typeof import('./src/components/feature/RemoveAccount/RemoveAccount.vue')['default']
    StatusMessage: typeof import('./src/components/base/StatusMessage/StatusMessage.vue')['default']
    TabviewGeneral: typeof import('./src/components/feature/TabviewGeneral/TabviewGeneral.vue')['default']
    TabviewHeader: typeof import('./src/components/pure/TabviewHeader/TabviewHeader.vue')['default']
    TabviewLicense: typeof import('./src/components/feature/TabviewLicense/TabviewLicense.vue')['default']
    TabviewPassword: typeof import('./src/components/feature/TabviewPassword/TabviewPassword.vue')['default']
    TabviewUserData: typeof import('./src/components/feature/TabviewUserData/TabviewUserData.vue')['default']
    Timezone: typeof import('./src/components/feature/Timezone/Timezone.vue')['default']
    'TSXUserProfile.ce': typeof import('./src/components/feature/TSXUserProfile/TSXUserProfile.ce.vue')['default']
  }
}
