// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * T​i​m​e​z​o​n​e
	 */
	timezone: string
	/**
	 * Y​o​u​r​ ​t​i​m​e​z​o​n​e​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​c​h​a​n​g​e​d
	 */
	timezoneInfo: string
	/**
	 * S​a​v​e
	 */
	save: string
	/**
	 * A​v​a​t​a​r
	 */
	avatar: string
	/**
	 * E​m​a​i​l
	 */
	email: string
	/**
	 * P​r​o​f​i​l​e
	 */
	profile: string
	/**
	 * E​d​i​t
	 */
	edit: string
	/**
	 * F​i​r​s​t​ ​n​a​m​e
	 */
	firstName: string
	/**
	 * L​a​s​t​ ​n​a​m​e
	 */
	lastName: string
	/**
	 * U​p​d​a​t​e​ ​p​a​s​s​w​o​r​d
	 */
	updatePassword: string
	/**
	 * E​d​i​t​ ​p​e​r​s​o​n​a​l​ ​i​n​f​o​r​m​a​t​i​o​n
	 */
	editPersonalInformation: string
	/**
	 * Y​o​u​r​ ​p​e​r​s​o​n​a​l​ ​i​n​f​o​r​m​a​t​i​o​n​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​c​h​a​n​g​e​d
	 */
	successPersonalInformation: string
	/**
	 * F​i​r​s​t​ ​n​a​m​e​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​3​ ​c​h​a​r​a​c​t​e​r​s​ ​l​o​n​g
	 */
	firstNameError: string
	/**
	 * L​a​s​t​ ​n​a​m​e​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​3​ ​c​h​a​r​a​c​t​e​r​s​ ​l​o​n​g
	 */
	lastNameError: string
	/**
	 * F​i​e​l​d​ ​s​h​o​u​l​d​ ​n​o​t​ ​b​e​ ​e​m​p​t​y
	 */
	emptyError: string
	/**
	 * R​e​m​o​v​e​ ​a​c​c​o​u​n​t
	 */
	removeAccount: string
	/**
	 * A​f​t​e​r​ ​r​e​m​o​v​i​n​g​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​y​o​u​ ​w​i​l​l​ ​l​o​s​e​ ​a​c​c​e​s​s​ ​t​o​ ​y​o​u​r​ ​s​e​r​v​e​r​,​ ​w​e​b​s​i​t​e​,​ ​b​l​a​c​k​l​i​s​t​,​ ​a​n​d​ ​l​o​g​ ​f​i​l​e​ ​m​o​n​i​t​o​r​s​ ​a​n​d​ ​t​o​ ​a​l​l​ ​h​i​s​t​o​r​i​c​a​l​ ​d​a​t​a​.
	 */
	removeAccountBody: string
	/**
	 * R​e​m​o​v​e​ ​m​y​ ​a​c​c​o​u​n​t
	 */
	removeAccountButton: string
	/**
	 * A​l​l​ ​y​o​u​ ​d​a​t​a​ ​w​i​l​l​ ​b​e​ ​r​e​m​o​v​e​d
	 */
	removeAccountAnnotationTitle: string
	/**
	 * A​f​t​e​r​ ​y​o​u​ ​r​e​m​o​v​e​ ​t​h​e​ ​a​c​c​o​u​n​t​ ​y​o​u​r​ ​p​l​a​n​ ​s​u​b​s​c​r​i​p​t​i​o​n​ ​w​i​l​l​ ​a​l​s​o​ ​b​e​ ​r​e​m​o​v​e​d​.​ ​B​e​ ​a​w​a​r​e​,​ ​a​c​c​o​u​n​t​ ​r​e​m​o​v​a​l​ ​i​s​ ​f​i​n​a​l​.​ ​T​h​e​r​e​ ​w​i​l​l​ ​b​e​ ​n​o​ ​w​a​y​ ​t​o​ ​r​e​s​t​o​r​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t​.
	 */
	removeAccountAnnotationContent: string
	/**
	 * E​n​t​e​r​ ​t​h​e​ ​p​a​s​s​w​o​r​d​ ​t​o​ ​c​o​n​f​i​r​m​ ​t​h​e​ ​r​e​m​o​v​a​l​ ​o​f​ ​t​h​e​ ​a​c​c​o​u​n​t
	 */
	enterPasswordConfirmRemove: string
	/**
	 * R​e​c​e​i​v​e​ ​3​6​0​ ​M​o​n​i​t​o​r​i​n​g​ ​u​p​d​a​t​e​s​ ​a​n​d​ ​c​o​m​m​e​r​c​i​a​l​ ​c​o​m​m​u​n​i​c​a​t​i​o​n
	 */
	consentHeadline: string
	/**
	 * W​e​b​P​r​o​s​ ​g​r​o​u​p​ ​c​o​m​p​a​n​i​e​s​ ​m​a​y​ ​s​t​o​r​e​ ​a​n​d​ ​p​r​o​c​e​s​s​ ​t​h​e​ ​d​a​t​a​ ​I​ ​p​r​o​v​i​d​e​ ​t​o​ ​d​e​l​i​v​e​r​ ​p​e​r​s​o​n​a​l​i​z​e​d​ ​m​a​r​k​e​t​i​n​g​ ​c​o​n​t​e​n​t​ ​s​u​c​h​ ​a​s​ ​n​e​w​s​l​e​t​t​e​r​s​ ​a​n​d​ ​i​n​d​i​v​i​d​u​a​l​ ​o​f​f​e​r​s​ ​a​c​c​o​r​d​i​n​g​ ​t​o​ ​t​h​e​ ​P​r​i​v​a​c​y​ ​P​o​l​i​c​y​.​ ​T​a​i​l​o​r​e​d​ ​o​f​f​e​r​i​n​g​s​ ​m​a​y​ ​b​e​ ​b​a​s​e​d​ ​o​n​ ​a​d​d​i​t​i​o​n​a​l​ ​i​n​f​o​r​m​a​t​i​o​n​ ​l​i​k​e​ ​u​s​a​g​e​ ​a​n​d​ ​b​e​h​a​v​i​o​r​ ​d​a​t​a​ ​(​P​r​o​f​i​l​i​n​g​)​.​ ​I​ ​c​a​n​ ​r​e​v​o​k​e​ ​t​h​i​s​ ​c​o​n​s​e​n​t​ ​a​t​ ​a​n​y​ ​t​i​m​e​ ​i​n​ ​t​h​e​ ​p​l​a​t​f​o​r​m​ ​p​r​e​f​e​r​e​n​c​e​s​.
	 */
	consentBody: string
	/**
	 * Y​o​u​r​ ​a​g​r​e​e​m​e​n​t​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​c​h​a​n​g​e​d
	 */
	consentSuccess: string
	/**
	 * Y​o​u​ ​h​a​v​e​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​u​n​s​u​b​s​c​r​i​b​e​d​ ​f​r​o​m​ ​o​u​r​ ​c​o​m​m​e​r​c​i​a​l​ ​c​o​m​m​u​n​i​c​a​t​i​o​n​.
	 */
	consentRevoke: string
	/**
	 * C​u​r​r​e​n​t​ ​P​a​s​s​w​o​r​d
	 */
	currentPassword: string
	/**
	 * N​e​w​ ​P​a​s​s​w​o​r​d
	 */
	newPassword: string
	/**
	 * C​o​n​f​i​r​m​ ​N​e​w​ ​P​a​s​s​w​o​r​d
	 */
	newPasswordConfirm: string
	/**
	 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​8​ ​c​h​a​r​a​c​t​e​r​s​ ​l​o​n​g
	 */
	passwordTooShort: string
	/**
	 * N​e​w​ ​P​a​s​s​w​o​r​d​s​ ​d​o​ ​n​o​t​ ​m​a​t​c​h
	 */
	passwordsNotMatch: string
	/**
	 * Y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​c​h​a​n​g​e​d
	 */
	successChangePassword: string
	/**
	 * A​c​t​i​v​e
	 */
	active: string
	/**
	 * C​a​n​c​e​l​e​d
	 */
	canceled: string
	/**
	 * C​l​o​s​e
	 */
	close: string
	/**
	 * N​e​x​t​ ​b​i​l​l​i​n​g​ ​d​a​t​e​ 
	 */
	activeDateText: string
	/**
	 * C​a​n​c​e​l​e​d​ ​s​i​n​c​e​ 
	 */
	canceledDateText: string
	/**
	 * m​o
	 */
	mo: string
	/**
	 * s​u​b​s​c​r​i​p​t​i​o​n​ ​d​e​t​a​i​l​s
	 */
	subscriptionDetails: string
	/**
	 * Y​o​u​r​ ​c​u​r​r​e​n​t​ ​p​l​a​n
	 */
	yourCurrentPlan: string
}

export type TranslationFunctions = {
	/**
	 * Timezone
	 */
	timezone: () => LocalizedString
	/**
	 * Your timezone has been successfully changed
	 */
	timezoneInfo: () => LocalizedString
	/**
	 * Save
	 */
	save: () => LocalizedString
	/**
	 * Avatar
	 */
	avatar: () => LocalizedString
	/**
	 * Email
	 */
	email: () => LocalizedString
	/**
	 * Profile
	 */
	profile: () => LocalizedString
	/**
	 * Edit
	 */
	edit: () => LocalizedString
	/**
	 * First name
	 */
	firstName: () => LocalizedString
	/**
	 * Last name
	 */
	lastName: () => LocalizedString
	/**
	 * Update password
	 */
	updatePassword: () => LocalizedString
	/**
	 * Edit personal information
	 */
	editPersonalInformation: () => LocalizedString
	/**
	 * Your personal information has been successfully changed
	 */
	successPersonalInformation: () => LocalizedString
	/**
	 * First name must be at least 3 characters long
	 */
	firstNameError: () => LocalizedString
	/**
	 * Last name must be at least 3 characters long
	 */
	lastNameError: () => LocalizedString
	/**
	 * Field should not be empty
	 */
	emptyError: () => LocalizedString
	/**
	 * Remove account
	 */
	removeAccount: () => LocalizedString
	/**
	 * After removing your account you will lose access to your server, website, blacklist, and log file monitors and to all historical data.
	 */
	removeAccountBody: () => LocalizedString
	/**
	 * Remove my account
	 */
	removeAccountButton: () => LocalizedString
	/**
	 * All you data will be removed
	 */
	removeAccountAnnotationTitle: () => LocalizedString
	/**
	 * After you remove the account your plan subscription will also be removed. Be aware, account removal is final. There will be no way to restore your account.
	 */
	removeAccountAnnotationContent: () => LocalizedString
	/**
	 * Enter the password to confirm the removal of the account
	 */
	enterPasswordConfirmRemove: () => LocalizedString
	/**
	 * Receive 360 Monitoring updates and commercial communication
	 */
	consentHeadline: () => LocalizedString
	/**
	 * WebPros group companies may store and process the data I provide to deliver personalized marketing content such as newsletters and individual offers according to the Privacy Policy. Tailored offerings may be based on additional information like usage and behavior data (Profiling). I can revoke this consent at any time in the platform preferences.
	 */
	consentBody: () => LocalizedString
	/**
	 * Your agreement has been successfully changed
	 */
	consentSuccess: () => LocalizedString
	/**
	 * You have successfully unsubscribed from our commercial communication.
	 */
	consentRevoke: () => LocalizedString
	/**
	 * Current Password
	 */
	currentPassword: () => LocalizedString
	/**
	 * New Password
	 */
	newPassword: () => LocalizedString
	/**
	 * Confirm New Password
	 */
	newPasswordConfirm: () => LocalizedString
	/**
	 * Password must be at least 8 characters long
	 */
	passwordTooShort: () => LocalizedString
	/**
	 * New Passwords do not match
	 */
	passwordsNotMatch: () => LocalizedString
	/**
	 * Your password has been successfully changed
	 */
	successChangePassword: () => LocalizedString
	/**
	 * Active
	 */
	active: () => LocalizedString
	/**
	 * Canceled
	 */
	canceled: () => LocalizedString
	/**
	 * Close
	 */
	close: () => LocalizedString
	/**
	 * Next billing date 
	 */
	activeDateText: () => LocalizedString
	/**
	 * Canceled since 
	 */
	canceledDateText: () => LocalizedString
	/**
	 * mo
	 */
	mo: () => LocalizedString
	/**
	 * subscription details
	 */
	subscriptionDetails: () => LocalizedString
	/**
	 * Your current plan
	 */
	yourCurrentPlan: () => LocalizedString
}

export type Formatters = {}
